name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - run: npm ci
      - name: test and build
        run: |
          npm run test
          npm run build

