name: TEST AND BUILD
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v3
      - name: install
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - name: test
        run: |
          npm ci
          npm run test
      - name: build
        run: npm run build
